"""NUeva tabla para usuarios con google o microsoft

Revision ID: 7ab94ad3a165
Revises: dd1615abe7fc
Create Date: 2025-03-17 08:49:54.839550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ab94ad3a165'
down_revision: Union[str, None] = 'dd1615abe7fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_ext',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('id_ext', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_ext')),
    sa.UniqueConstraint('email', name=op.f('uq_user_ext_email')),
    schema='public'
    )
    op.drop_constraint('fk_order_products_product_id_products', 'order_products', type_='foreignkey')
    op.drop_constraint('fk_order_products_order_id_orders', 'order_products', type_='foreignkey')
    op.create_foreign_key(op.f('fk_order_products_order_id_orders'), 'order_products', 'orders', ['order_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(op.f('fk_order_products_product_id_products'), 'order_products', 'products', ['product_id'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('orders', sa.Column('user_ext_id', sa.Integer(), nullable=True))
    op.alter_column('orders', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('fk_orders_user_id_users', 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('fk_orders_user_id_users'), 'orders', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(op.f('fk_orders_user_ext_id_user_ext'), 'orders', 'user_ext', ['user_ext_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_orders_user_ext_id_user_ext'), 'orders', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_orders_user_id_users'), 'orders', schema='public', type_='foreignkey')
    op.create_foreign_key('fk_orders_user_id_users', 'orders', 'users', ['user_id'], ['id'])
    op.alter_column('orders', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('orders', 'user_ext_id')
    op.drop_constraint(op.f('fk_order_products_product_id_products'), 'order_products', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_order_products_order_id_orders'), 'order_products', schema='public', type_='foreignkey')
    op.create_foreign_key('fk_order_products_order_id_orders', 'order_products', 'orders', ['order_id'], ['id'])
    op.create_foreign_key('fk_order_products_product_id_products', 'order_products', 'products', ['product_id'], ['id'])
    op.drop_table('user_ext', schema='public')
    # ### end Alembic commands ###
