"""Descripción de la migración

Revision ID: dd1615abe7fc
Revises: 1121be02d74f
Create Date: 2025-03-11 09:38:45.433085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd1615abe7fc'
down_revision: Union[str, None] = '1121be02d74f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_order_products_order_id_orders', 'order_products', type_='foreignkey')
    op.drop_constraint('fk_order_products_product_id_products', 'order_products', type_='foreignkey')
    op.create_foreign_key(op.f('fk_order_products_product_id_products'), 'order_products', 'products', ['product_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(op.f('fk_order_products_order_id_orders'), 'order_products', 'orders', ['order_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('fk_orders_user_id_users', 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('fk_orders_user_id_users'), 'orders', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_orders_user_id_users'), 'orders', schema='public', type_='foreignkey')
    op.create_foreign_key('fk_orders_user_id_users', 'orders', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_order_products_order_id_orders'), 'order_products', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_order_products_product_id_products'), 'order_products', schema='public', type_='foreignkey')
    op.create_foreign_key('fk_order_products_product_id_products', 'order_products', 'products', ['product_id'], ['id'])
    op.create_foreign_key('fk_order_products_order_id_orders', 'order_products', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
